-- Enable LuaJIT faster load times
pcall(require, "luarocks.loader")

require("wesbragagt.plugins")
require("wesbragagt.performance")
require("wesbragagt.options")
require("wesbragagt.maps")
require("wesbragagt.autorun")
require("wesbragagt.colorscheme")
require("wesbragagt._icons")
require("wesbragagt._indentline")
require("wesbragagt._statusline")
require("wesbragagt.vimux")
require("wesbragagt.snippets")
require("wesbragagt._null-ls")
require("wesbragagt._trouble")
require("wesbragagt.debug")
require("wesbragagt._harpoon")
require("wesbragagt._jest")
