set norelativenumber
set nowrap
set updatetime=300
" sets vsp to split right by default
set splitright
set hidden
set mouse=a
set noswapfile
set nobackup
set undodir=~/.vim/undodir
set undofile
set incsearch
set termguicolors
set showcmd
set tabstop=2
set softtabstop=2
set shiftwidth=2
set smartcase
set noerrorbells
set smartindent
set expandtab
set scrolloff=8
set number
set autochdir
set colorcolumn=80
set termguicolors
